AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  HTH2024ReelItBackDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: HTH2024Table
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  DownloadExcelFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: download_excel.app.lambda_handler
      Runtime: python3.12
      Environment:
        Variables:
          TABLE_NAME: !Ref HTH2024ReelItBackDB
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref HTH2024ReelItBackDB
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /trigger
            Method: get

  UploadExcelFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: upload_excel.app.lambda_handler
      Runtime: python3.12
      Environment:
        Variables:
          TABLE_NAME: !Ref HTH2024ReelItBackDB
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref HTH2024ReelItBackDB
      Events:
        UploadExcelApi:
          Type: Api
          Properties:
            Path: /upload
            Method: post